// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"isvacbanned/domain/telegrambot"
	"sync"
)

// Ensure, that FollowPlayerUserPersistenceGatewayMock does implement telegrambot.FollowPlayerUserPersistenceGateway.
// If this is not the case, regenerate this file with moq.
var _ telegrambot.FollowPlayerUserPersistenceGateway = &FollowPlayerUserPersistenceGatewayMock{}

// FollowPlayerUserPersistenceGatewayMock is a mock implementation of telegrambot.FollowPlayerUserPersistenceGateway.
//
// 	func TestSomethingThatUsesFollowPlayerUserPersistenceGateway(t *testing.T) {
//
// 		// make and configure a mocked telegrambot.FollowPlayerUserPersistenceGateway
// 		mockedFollowPlayerUserPersistenceGateway := &FollowPlayerUserPersistenceGatewayMock{
// 			ActivateUserFunc: func(ctx context.Context, userID int64) (int64, error) {
// 				panic("mock out the ActivateUser method")
// 			},
// 			CreateUserFunc: func(ctx context.Context, firstName string, username string, telegramID int64) (int64, error) {
// 				panic("mock out the CreateUser method")
// 			},
// 			GetUserIDFunc: func(ctx context.Context, telegramID int64) (int64, error) {
// 				panic("mock out the GetUserID method")
// 			},
// 		}
//
// 		// use mockedFollowPlayerUserPersistenceGateway in code that requires telegrambot.FollowPlayerUserPersistenceGateway
// 		// and then make assertions.
//
// 	}
type FollowPlayerUserPersistenceGatewayMock struct {
	// ActivateUserFunc mocks the ActivateUser method.
	ActivateUserFunc func(ctx context.Context, userID int64) (int64, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, firstName string, username string, telegramID int64) (int64, error)

	// GetUserIDFunc mocks the GetUserID method.
	GetUserIDFunc func(ctx context.Context, telegramID int64) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// ActivateUser holds details about calls to the ActivateUser method.
		ActivateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FirstName is the firstName argument value.
			FirstName string
			// Username is the username argument value.
			Username string
			// TelegramID is the telegramID argument value.
			TelegramID int64
		}
		// GetUserID holds details about calls to the GetUserID method.
		GetUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TelegramID is the telegramID argument value.
			TelegramID int64
		}
	}
	lockActivateUser sync.RWMutex
	lockCreateUser   sync.RWMutex
	lockGetUserID    sync.RWMutex
}

// ActivateUser calls ActivateUserFunc.
func (mock *FollowPlayerUserPersistenceGatewayMock) ActivateUser(ctx context.Context, userID int64) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockActivateUser.Lock()
	mock.calls.ActivateUser = append(mock.calls.ActivateUser, callInfo)
	mock.lockActivateUser.Unlock()
	if mock.ActivateUserFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.ActivateUserFunc(ctx, userID)
}

// ActivateUserCalls gets all the calls that were made to ActivateUser.
// Check the length with:
//     len(mockedFollowPlayerUserPersistenceGateway.ActivateUserCalls())
func (mock *FollowPlayerUserPersistenceGatewayMock) ActivateUserCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockActivateUser.RLock()
	calls = mock.calls.ActivateUser
	mock.lockActivateUser.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *FollowPlayerUserPersistenceGatewayMock) CreateUser(ctx context.Context, firstName string, username string, telegramID int64) (int64, error) {
	callInfo := struct {
		Ctx        context.Context
		FirstName  string
		Username   string
		TelegramID int64
	}{
		Ctx:        ctx,
		FirstName:  firstName,
		Username:   username,
		TelegramID: telegramID,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	if mock.CreateUserFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.CreateUserFunc(ctx, firstName, username, telegramID)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//     len(mockedFollowPlayerUserPersistenceGateway.CreateUserCalls())
func (mock *FollowPlayerUserPersistenceGatewayMock) CreateUserCalls() []struct {
	Ctx        context.Context
	FirstName  string
	Username   string
	TelegramID int64
} {
	var calls []struct {
		Ctx        context.Context
		FirstName  string
		Username   string
		TelegramID int64
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// GetUserID calls GetUserIDFunc.
func (mock *FollowPlayerUserPersistenceGatewayMock) GetUserID(ctx context.Context, telegramID int64) (int64, error) {
	callInfo := struct {
		Ctx        context.Context
		TelegramID int64
	}{
		Ctx:        ctx,
		TelegramID: telegramID,
	}
	mock.lockGetUserID.Lock()
	mock.calls.GetUserID = append(mock.calls.GetUserID, callInfo)
	mock.lockGetUserID.Unlock()
	if mock.GetUserIDFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.GetUserIDFunc(ctx, telegramID)
}

// GetUserIDCalls gets all the calls that were made to GetUserID.
// Check the length with:
//     len(mockedFollowPlayerUserPersistenceGateway.GetUserIDCalls())
func (mock *FollowPlayerUserPersistenceGatewayMock) GetUserIDCalls() []struct {
	Ctx        context.Context
	TelegramID int64
} {
	var calls []struct {
		Ctx        context.Context
		TelegramID int64
	}
	mock.lockGetUserID.RLock()
	calls = mock.calls.GetUserID
	mock.lockGetUserID.RUnlock()
	return calls
}
