// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"isvacbanned/domain/telegrambot"
	"sync"
)

// Ensure, that StopNotificationsUserPersistenceGatewayMock does implement telegrambot.StopNotificationsUserPersistenceGateway.
// If this is not the case, regenerate this file with moq.
var _ telegrambot.StopNotificationsUserPersistenceGateway = &StopNotificationsUserPersistenceGatewayMock{}

// StopNotificationsUserPersistenceGatewayMock is a mock implementation of telegrambot.StopNotificationsUserPersistenceGateway.
//
// 	func TestSomethingThatUsesStopNotificationsUserPersistenceGateway(t *testing.T) {
//
// 		// make and configure a mocked telegrambot.StopNotificationsUserPersistenceGateway
// 		mockedStopNotificationsUserPersistenceGateway := &StopNotificationsUserPersistenceGatewayMock{
// 			CreateUserFunc: func(ctx context.Context, firstName string, username string, telegramID int64) (int64, error) {
// 				panic("mock out the CreateUser method")
// 			},
// 			GetUserIDFunc: func(ctx context.Context, telegramID int64) (int64, error) {
// 				panic("mock out the GetUserID method")
// 			},
// 			InactivateUserFunc: func(ctx context.Context, userID int64) (int64, error) {
// 				panic("mock out the InactivateUser method")
// 			},
// 		}
//
// 		// use mockedStopNotificationsUserPersistenceGateway in code that requires telegrambot.StopNotificationsUserPersistenceGateway
// 		// and then make assertions.
//
// 	}
type StopNotificationsUserPersistenceGatewayMock struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, firstName string, username string, telegramID int64) (int64, error)

	// GetUserIDFunc mocks the GetUserID method.
	GetUserIDFunc func(ctx context.Context, telegramID int64) (int64, error)

	// InactivateUserFunc mocks the InactivateUser method.
	InactivateUserFunc func(ctx context.Context, userID int64) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FirstName is the firstName argument value.
			FirstName string
			// Username is the username argument value.
			Username string
			// TelegramID is the telegramID argument value.
			TelegramID int64
		}
		// GetUserID holds details about calls to the GetUserID method.
		GetUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TelegramID is the telegramID argument value.
			TelegramID int64
		}
		// InactivateUser holds details about calls to the InactivateUser method.
		InactivateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
	}
	lockCreateUser     sync.RWMutex
	lockGetUserID      sync.RWMutex
	lockInactivateUser sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *StopNotificationsUserPersistenceGatewayMock) CreateUser(ctx context.Context, firstName string, username string, telegramID int64) (int64, error) {
	callInfo := struct {
		Ctx        context.Context
		FirstName  string
		Username   string
		TelegramID int64
	}{
		Ctx:        ctx,
		FirstName:  firstName,
		Username:   username,
		TelegramID: telegramID,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	if mock.CreateUserFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.CreateUserFunc(ctx, firstName, username, telegramID)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//     len(mockedStopNotificationsUserPersistenceGateway.CreateUserCalls())
func (mock *StopNotificationsUserPersistenceGatewayMock) CreateUserCalls() []struct {
	Ctx        context.Context
	FirstName  string
	Username   string
	TelegramID int64
} {
	var calls []struct {
		Ctx        context.Context
		FirstName  string
		Username   string
		TelegramID int64
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// GetUserID calls GetUserIDFunc.
func (mock *StopNotificationsUserPersistenceGatewayMock) GetUserID(ctx context.Context, telegramID int64) (int64, error) {
	callInfo := struct {
		Ctx        context.Context
		TelegramID int64
	}{
		Ctx:        ctx,
		TelegramID: telegramID,
	}
	mock.lockGetUserID.Lock()
	mock.calls.GetUserID = append(mock.calls.GetUserID, callInfo)
	mock.lockGetUserID.Unlock()
	if mock.GetUserIDFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.GetUserIDFunc(ctx, telegramID)
}

// GetUserIDCalls gets all the calls that were made to GetUserID.
// Check the length with:
//     len(mockedStopNotificationsUserPersistenceGateway.GetUserIDCalls())
func (mock *StopNotificationsUserPersistenceGatewayMock) GetUserIDCalls() []struct {
	Ctx        context.Context
	TelegramID int64
} {
	var calls []struct {
		Ctx        context.Context
		TelegramID int64
	}
	mock.lockGetUserID.RLock()
	calls = mock.calls.GetUserID
	mock.lockGetUserID.RUnlock()
	return calls
}

// InactivateUser calls InactivateUserFunc.
func (mock *StopNotificationsUserPersistenceGatewayMock) InactivateUser(ctx context.Context, userID int64) (int64, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockInactivateUser.Lock()
	mock.calls.InactivateUser = append(mock.calls.InactivateUser, callInfo)
	mock.lockInactivateUser.Unlock()
	if mock.InactivateUserFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.InactivateUserFunc(ctx, userID)
}

// InactivateUserCalls gets all the calls that were made to InactivateUser.
// Check the length with:
//     len(mockedStopNotificationsUserPersistenceGateway.InactivateUserCalls())
func (mock *StopNotificationsUserPersistenceGatewayMock) InactivateUserCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockInactivateUser.RLock()
	calls = mock.calls.InactivateUser
	mock.lockInactivateUser.RUnlock()
	return calls
}
