// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"isvacbanned/domain/entities"
	"isvacbanned/domain/job"
	"sync"
)

// Ensure, that FollowedUsersJobSteamGatewayMock does implement job.FollowedUsersJobSteamGateway.
// If this is not the case, regenerate this file with moq.
var _ job.FollowedUsersJobSteamGateway = &FollowedUsersJobSteamGatewayMock{}

// FollowedUsersJobSteamGatewayMock is a mock implementation of job.FollowedUsersJobSteamGateway.
//
// 	func TestSomethingThatUsesFollowedUsersJobSteamGateway(t *testing.T) {
//
// 		// make and configure a mocked job.FollowedUsersJobSteamGateway
// 		mockedFollowedUsersJobSteamGateway := &FollowedUsersJobSteamGatewayMock{
// 			GetPlayersCurrentNicknamesFunc: func(steamIDs ...string) (entities.PlayerInfo, error) {
// 				panic("mock out the GetPlayersCurrentNicknames method")
// 			},
// 			GetPlayersStatusFunc: func(steamIDs ...string) (entities.Player, error) {
// 				panic("mock out the GetPlayersStatus method")
// 			},
// 		}
//
// 		// use mockedFollowedUsersJobSteamGateway in code that requires job.FollowedUsersJobSteamGateway
// 		// and then make assertions.
//
// 	}
type FollowedUsersJobSteamGatewayMock struct {
	// GetPlayersCurrentNicknamesFunc mocks the GetPlayersCurrentNicknames method.
	GetPlayersCurrentNicknamesFunc func(steamIDs ...string) (entities.PlayerInfo, error)

	// GetPlayersStatusFunc mocks the GetPlayersStatus method.
	GetPlayersStatusFunc func(steamIDs ...string) (entities.Player, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPlayersCurrentNicknames holds details about calls to the GetPlayersCurrentNicknames method.
		GetPlayersCurrentNicknames []struct {
			// SteamIDs is the steamIDs argument value.
			SteamIDs []string
		}
		// GetPlayersStatus holds details about calls to the GetPlayersStatus method.
		GetPlayersStatus []struct {
			// SteamIDs is the steamIDs argument value.
			SteamIDs []string
		}
	}
	lockGetPlayersCurrentNicknames sync.RWMutex
	lockGetPlayersStatus           sync.RWMutex
}

// GetPlayersCurrentNicknames calls GetPlayersCurrentNicknamesFunc.
func (mock *FollowedUsersJobSteamGatewayMock) GetPlayersCurrentNicknames(steamIDs ...string) (entities.PlayerInfo, error) {
	callInfo := struct {
		SteamIDs []string
	}{
		SteamIDs: steamIDs,
	}
	mock.lockGetPlayersCurrentNicknames.Lock()
	mock.calls.GetPlayersCurrentNicknames = append(mock.calls.GetPlayersCurrentNicknames, callInfo)
	mock.lockGetPlayersCurrentNicknames.Unlock()
	if mock.GetPlayersCurrentNicknamesFunc == nil {
		var (
			playerInfoOut entities.PlayerInfo
			errOut        error
		)
		return playerInfoOut, errOut
	}
	return mock.GetPlayersCurrentNicknamesFunc(steamIDs...)
}

// GetPlayersCurrentNicknamesCalls gets all the calls that were made to GetPlayersCurrentNicknames.
// Check the length with:
//     len(mockedFollowedUsersJobSteamGateway.GetPlayersCurrentNicknamesCalls())
func (mock *FollowedUsersJobSteamGatewayMock) GetPlayersCurrentNicknamesCalls() []struct {
	SteamIDs []string
} {
	var calls []struct {
		SteamIDs []string
	}
	mock.lockGetPlayersCurrentNicknames.RLock()
	calls = mock.calls.GetPlayersCurrentNicknames
	mock.lockGetPlayersCurrentNicknames.RUnlock()
	return calls
}

// GetPlayersStatus calls GetPlayersStatusFunc.
func (mock *FollowedUsersJobSteamGatewayMock) GetPlayersStatus(steamIDs ...string) (entities.Player, error) {
	callInfo := struct {
		SteamIDs []string
	}{
		SteamIDs: steamIDs,
	}
	mock.lockGetPlayersStatus.Lock()
	mock.calls.GetPlayersStatus = append(mock.calls.GetPlayersStatus, callInfo)
	mock.lockGetPlayersStatus.Unlock()
	if mock.GetPlayersStatusFunc == nil {
		var (
			playerOut entities.Player
			errOut    error
		)
		return playerOut, errOut
	}
	return mock.GetPlayersStatusFunc(steamIDs...)
}

// GetPlayersStatusCalls gets all the calls that were made to GetPlayersStatus.
// Check the length with:
//     len(mockedFollowedUsersJobSteamGateway.GetPlayersStatusCalls())
func (mock *FollowedUsersJobSteamGatewayMock) GetPlayersStatusCalls() []struct {
	SteamIDs []string
} {
	var calls []struct {
		SteamIDs []string
	}
	mock.lockGetPlayersStatus.RLock()
	calls = mock.calls.GetPlayersStatus
	mock.lockGetPlayersStatus.RUnlock()
	return calls
}
